# Generated by Django 4.2.1 on 2023-07-11 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("student_profile", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("internal", "Internal"),
                            ("final", "Final"),
                            ("practical", "Practical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("total_marks", models.IntegerField(default=100)),
                ("pass_marks", models.IntegerField(default=45)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "course_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.coursesession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GradeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks_obtained", models.IntegerField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="grades.exam"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_profile.studentprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("exam", "student")},
            },
        ),
    ]
