# Generated by Django 4.2.1 on 2023-07-11 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/students/"
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=20)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("address", models.CharField(max_length=100)),
                ("academics", models.TextField()),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "symbol_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("1st", "1st"),
                            ("2nd", "2nd"),
                            ("3rd", "3rd"),
                            ("4th", "4th"),
                            ("5th", "5th"),
                            ("6th", "6th"),
                            ("7th", "7th"),
                            ("8th", "8th"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
