# Generated by Django 4.2.13 on 2024-07-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="face_encoding",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
